# Site settings
title: Malik Singleton
description: '<p>I do data and design work</p><hr><p><a href="/cv/info-design/">Info Design</a><br><a href="/cv/data-science/">Data Science</a><br><a href="/cv/instruction/">Instruction</a></p><hr><p><a href="/cv/experience/">Experience</a><br><a href="/cv/education/">Education</a><br><a href="/cv/examples/">Examples</a></p>'
url: https://mrsingleton.github.io
theme: jekyll-theme-minimal
email: malik@nyu.edu
keywords: "resume site, curriculum vitae example, work history online, work experience website, personal information, malik singleton, professional background"
skills: "Data Science - Web Development - Information Architecture - User Experience"
meta_author: Singleton Malik
